[tool.poetry]
name = "neuralamp-envrironment"
version = "0.1.0"
description = "neuralamp envrironment project"
authors = ["Nick Mazurkin <mazurkin@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.12"

[tool.poetry.group.platform.dependencies]
setuptools = "80.3.1"

[tool.poetry.group.util.dependencies]
tqdm = "4.67.1"
argh = "0.29.4"
pydantic = "2.12.5"
semver = "3.0.4"
pre-commit = "4.5.1"

[tool.poetry.group.pytorch.dependencies]
torch = {url="https://download.pytorch.org/whl/cu130/torch-2.9.1%2Bcu130-cp312-cp312-manylinux_2_28_x86_64.whl"}
torchaudio = {url="https://download.pytorch.org/whl/cu130/torchaudio-2.9.1%2Bcu130-cp312-cp312-manylinux_2_28_x86_64.whl"}
torchcodec = {url="https://download.pytorch.org/whl/cu130/torchcodec-0.9.1%2Bcu130-cp312-cp312-manylinux_2_28_x86_64.whl"}

[tool.poetry.group.lightning.dependencies]
pytorch-lightning = "2.6.1"
torchmetrics = "1.8.2"
litlogger = "2026.3.17"

[tool.poetry.group.nam.dependencies]
neural-amp-modeler = "0.13.0"

[tool.poetry.group.audio.dependencies]
wavio = "0.0.9"
sounddevice = "0.5.5"

[tool.poetry.group.huggingface.dependencies]
huggingface_hub = {version="0.36.0", extras=["cli"]}
transformers = {version="4.57.6", extras=["torch"]}

[tool.poetry.group.format.dependencies]
pyarrow = "22.0.0"
pyyaml = "6.0.3"
h5py = "3.16.0"

[tool.poetry.group.tensorboard.dependencies]
tensorboard = "2.20.0"

[tool.poetry.group.dev-lint.dependencies]
flake8 = "7.3.0"
pylint = "4.0.4"

[tool.poetry.group.dev-test.dependencies]
pytest = "8.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "slow: the tests takes a long time (deselect with '-m \"not long\"')",
]
